### PR TITLE
Remove Grab-and-Drag section

### PR DESCRIPTION
**Pull request by bialpio**
The entire Grab and drag section relies only on virtual hit test (combined
result needs to contain `"virtualTarget"` key which is only present for
virtual hit test) which is not strictly related to the hit test API as it
is something that needs to be handled purely by the application in
JavaScript.

### CODE REVIEW

**Comment by mounirlamouri** [comment]
LGTM. This could make an interesting sample but shouldn't be in the explainer.

**Comment by blairmacintyre** [comment]
I'm not sure I agree with the move to remove this as a use-case;  it seems like one of the more obvious ones.  While the proposal is to change the API, it would seem that any useful API would support this use.  Certainly, it will need to use app-side content/framework-specific features to test against virtual content, but doing hit-testing against the world during the drag should be doable.

**Comment by bialpio** [comment]
@blairmacintyre I'm not sure if I understand the concern here. Virtual hit test is (and already was) explicitly out of scope for WebXR-provided hit test API - we only mentioned it for the sake of completeness (namely that it is possible to write a combined hit test that takes into account both virtual scene and user's environment) and this PR does not modify that. The entire section that is being removed is useful for demonstration purposes (maybe in [input explainer](https://github.com/immersive-web/webxr/blob/master/input-explainer.md)) , but in my opinion does not fit in the hit testing explainer.

**Comment by blairmacintyre** [comment]
I would agree the detailed example code should go;  I think I misread @mounirlamouri's comment.  I wasn't suggesting we keep virtual hit test, just that I thought you both were saying that the mention of this as a use case be removed.

**Comment by bialpio** [comment]
Got it. I'm merging the PR now, we can always bring the text back if people disagree.

**Pull request merged**
