### PR TITLE
Require user activation

### PR DESCRIPTION
**Pull request by ddorwin**

### CODE REVIEW

**Comment by blairmacintyre** [comment]
I'd like to talk through user-activation a bit.  I've always been concerned about it.

Here's my concern:  to me, user activation (i.e., requiring that the user has clicked something) seems completely worthless as a form of consent, so I'm not sure I understand why we want it.  I could fire off a session request from ANY click event, regardless of what the user clicked on, so it seems completely meaningless.

We should be requiring that, much like cameras or microphones or location, the BROWSER obtain informed consent from the user.  Stress on "informed" (e.g., they should really understand what information is, or isn't being sent to the web page if they give consent, which may require some education ... we shouldn't piggyback on existing concept like video, which imply the wrong information being available, something I recently talked about on my blog, actually).

Assuming we are going to require permission to access XR devices, is it simply that we don't want a page requesting an XR session immediately, and triggering a permission request from the user?

**Comment by ddorwin** [comment]
User activation certainly isn't a replacement for other consent, but it is at least a bare minimum - similar to frame focus [1]. Yes, pages probably shouldn't be triggering permission dialogs or similar without at least some interaction, though this isn't always the case.

These issues will be explored further in the new https://github.com/immersive-web/privacy-and-security repo. For now, I think it makes sense to land this then iterate as we develop a better picture for user privacy and security. (It also matches Chrome's implementation.) It is easier to _remove_ such a requirement than it is to add one. Also, we may get feedback from developers on legitimate use cases where this is a problem, and that can help inform the discussion.

[1] Frame focus does not appear to be mentioned in either this explainer or the core spec. I'll add a note to https://github.com/immersive-web/privacy-and-security/issues/9.

**Comment by bialpio** [comment]
I'd like to close this PR as it's is out-of-date and requiring user activation might not fit the current model of subscription-based hit test. My understanding of requiring user activation is that it's there to prevent APIs from performing operations that can be considered nuisance to the user - hit test does not really fit that definition (the app can already draw what it wants using the GL context, it doesn't need a hit test API to become a nuisance). There are potential malicious things the app could do (like subscribing to hit tests to drain battery life / increase computing cost), but I feel that it should be mitigated by requiring user consent. If that's not sufficient, we might want to consider other approaches that do not require user activation.

**Comment by ddorwin** [comment]
This PR wsa about requiring user activation when requesting a session capable of hit-test. This is now addressed by the `"immersive-ar"` session in the main spec.

**Pull request closed without merging**
